#!/usr/bin/env node
// Regenerates the table in docs/CAPABILITY_MATRIX.md from electron/mcpServer.js.
//   node scripts/capability-matrix.mjs           print the summary
//   node scripts/capability-matrix.mjs --write   rewrite the generated block
//   node scripts/capability-matrix.mjs --check   exit 1 if the doc or the classification is stale
// Names, descriptions and schemas come from evaluating createToolDefinitions();
// group, verbs, class and notes come from scripts/capability-matrix.classes.json.
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const DOC = path.join(ROOT, 'docs/CAPABILITY_MATRIX.md')
const START = '<!-- capability-matrix:start (generated by scripts/capability-matrix.mjs; edit the classes JSON, not this block) -->'
const END = '<!-- capability-matrix:end -->'
const CLASS_VALUES = ['exists', 'adapter', 'build']

function sliceFunction(src, header) {
  const start = src.indexOf(header)
  if (start < 0) throw new Error(`${header} not found in mcpServer.js`)
  const end = src.indexOf('\n}\n', start)
  return src.slice(start, end + 2)
}

// Constants the definitions reference (enum lists) resolve to placeholders: only
// names, descriptions and property keys are read from the result.
export function extractTools(src) {
  const scope = new Proxy({}, {
    has: (_, key) => typeof key === 'string' && !(key in globalThis),
    get: (_, key) => (key === Symbol.unscopables ? undefined : `<${String(key)}>`),
  })
  const body = sliceFunction(src, 'function createToolDefinitions() {')
  return new Function('scope', `with (scope) { ${body}\nreturn createToolDefinitions() }`)(scope)
}

export function extractWritable(src) {
  const marker = 'const MCP_ACTION_PLAN_WRITABLE_TOOLS = '
  const start = src.indexOf(marker)
  if (start < 0) throw new Error('MCP_ACTION_PLAN_WRITABLE_TOOLS not found')
  const end = src.indexOf('])', start)
  return new Function(`return ${src.slice(start + marker.length, end + 2)}`)()
}

function previewSupport(tool) {
  const prop = tool.inputSchema?.properties?.previewOnly
  if (!prop) return '—'
  const text = `${prop.description || ''} ${tool.description || ''}`
  return /defaults? to (true|previewonly|preview)/i.test(text) ? 'yes, default' : 'yes'
}

function firstSentence(text) {
  const match = String(text).match(/^.*?[.!?](\s|$)/)
  const sentence = (match ? match[0] : String(text)).trim()
  return sentence.length > 140 ? `${sentence.slice(0, 137)}…` : sentence
}

const cell = (text) => String(text).replace(/\|/g, '\\|').replace(/\n/g, ' ')

export function validate(tools, classes) {
  const problems = []
  const names = new Set(tools.map((tool) => tool.name))
  if (names.size !== tools.length) problems.push('duplicate tool names in createToolDefinitions()')
  for (const name of names) if (!classes.tools[name]) problems.push(`unclassified tool: ${name}`)
  for (const [name, entry] of Object.entries(classes.tools)) {
    if (!names.has(name)) problems.push(`classified tool no longer exists: ${name}`)
    if (!CLASS_VALUES.includes(entry.class)) problems.push(`${name}: class must be one of ${CLASS_VALUES.join(', ')}`)
    for (const verb of entry.verbs) if (!classes.verbs[verb]) problems.push(`${name}: unknown verb ${verb}`)
  }
  for (const item of classes.build) {
    if (names.has(item.name)) problems.push(`build item already exists as a tool: ${item.name}`)
    for (const verb of item.verbs) if (!classes.verbs[verb]) problems.push(`build ${item.name}: unknown verb ${verb}`)
  }
  return problems
}

export function summarize(tools, writable, classes) {
  const byClass = Object.fromEntries(CLASS_VALUES.map((value) => [value, 0]))
  for (const tool of tools) byClass[classes.tools[tool.name].class] += 1
  byClass.build += classes.build.length
  const verbRows = Object.entries(classes.verbs).map(([id, label]) => {
    const mapped = tools.filter((tool) => classes.tools[tool.name].verbs.includes(id))
    return {
      id,
      label,
      exists: mapped.filter((tool) => classes.tools[tool.name].class === 'exists').map((tool) => tool.name),
      adapter: mapped.filter((tool) => classes.tools[tool.name].class === 'adapter').map((tool) => tool.name),
      build: classes.build.filter((item) => item.verbs.includes(id)).map((item) => `${item.name} (${item.spec})`),
    }
  })
  return {
    toolCount: tools.length,
    withPreviewOnly: tools.filter((tool) => tool.inputSchema?.properties?.previewOnly).length,
    withAnnotations: tools.filter((tool) => tool.annotations).length,
    planWritable: tools.filter((tool) => writable.has(tool.name)).length,
    noVerb: tools.filter((tool) => classes.tools[tool.name].verbs.length === 0).length,
    byClass,
    verbRows,
    verbsWithoutExisting: verbRows.filter((row) => row.exists.length === 0),
  }
}

export function render(tools, writable, classes) {
  const summary = summarize(tools, writable, classes)
  const verbLabel = (id) => `${id} ${classes.verbs[id]}`
  const lines = [START, '']
  lines.push(`**${summary.toolCount} tools** in \`createToolDefinitions()\`; ${summary.withPreviewOnly} accept \`previewOnly\`; ${summary.planWritable} are in \`MCP_ACTION_PLAN_WRITABLE_TOOLS\`; ${summary.withAnnotations} carry MCP \`annotations\`.`, '')
  lines.push('### Every Velorn tool', '')
  lines.push('| # | Tool | Group | Contract verbs | Class | previewOnly | In plans | What it does | Notes |')
  lines.push('| --- | --- | --- | --- | --- | --- | --- | --- | --- |')
  tools.forEach((tool, index) => {
    const entry = classes.tools[tool.name]
    const verbs = entry.verbs.length ? entry.verbs.map(verbLabel).join('; ') : '—'
    lines.push(`| ${index + 1} | \`${tool.name}\` | ${entry.group} | ${verbs} | ${entry.class} | ${previewSupport(tool)} | ${writable.has(tool.name) ? 'yes' : '—'} | ${cell(firstSentence(tool.description))} | ${cell(entry.note)} |`)
  })
  lines.push('', '### Missing: what the contract needs that no Velorn tool provides (`build`)', '')
  lines.push('| Item | Contract verbs | Built by | Notes |', '| --- | --- | --- | --- |')
  for (const item of classes.build) {
    lines.push(`| \`${item.name}\` | ${item.verbs.map(verbLabel).join('; ')} | ${item.spec} | ${cell(item.note)} |`)
  }
  lines.push('', '### Summary', '')
  lines.push('| Class | Count |', '| --- | --- |')
  lines.push(`| exists | ${summary.byClass.exists} (of which ${summary.noVerb} serve no contract verb and stay in the expert profile) |`)
  lines.push(`| adapter | ${summary.byClass.adapter} |`)
  lines.push(`| build | ${summary.byClass.build} (items above; none is a Velorn tool) |`)
  lines.push('', '| Verb | `exists` tools | `adapter` tools | `build` items |', '| --- | --- | --- | --- |')
  for (const row of summary.verbRows) {
    lines.push(`| ${row.id} ${row.label} | ${row.exists.length} | ${row.adapter.length} | ${row.build.length ? row.build.join('; ') : '—'} |`)
  }
  lines.push('', '**Contract verbs with no `exists` tool:** ' + summary.verbsWithoutExisting.map((row) => `${row.id} ${row.label}`).join(', ') + '.', '', END)
  return { markdown: lines.join('\n'), summary }
}

export function load(root = ROOT) {
  const src = fs.readFileSync(path.join(root, 'electron/mcpServer.js'), 'utf8')
  const classes = JSON.parse(fs.readFileSync(path.join(root, 'scripts/capability-matrix.classes.json'), 'utf8'))
  return { tools: extractTools(src), writable: extractWritable(src), classes }
}

export function spliceDoc(doc, block) {
  const start = doc.indexOf(START)
  const end = doc.indexOf(END)
  if (start < 0 || end < start) throw new Error('generated-block markers not found in docs/CAPABILITY_MATRIX.md')
  return doc.slice(0, start) + block + doc.slice(end + END.length)
}

function main(argv) {
  const { tools, writable, classes } = load()
  const problems = validate(tools, classes)
  if (problems.length) {
    console.error(problems.join('\n'))
    return 1
  }
  const { markdown, summary } = render(tools, writable, classes)
  console.log(`tools in createToolDefinitions(): ${summary.toolCount} (unique names)`)
  console.log(`accept previewOnly: ${summary.withPreviewOnly}; in MCP_ACTION_PLAN_WRITABLE_TOOLS: ${summary.planWritable}; with annotations: ${summary.withAnnotations}`)
  console.log(`class exists: ${summary.byClass.exists} (no contract verb: ${summary.noVerb}); adapter: ${summary.byClass.adapter}; build items: ${summary.byClass.build}`)
  console.log(`verbs with no exists tool: ${summary.verbsWithoutExisting.map((row) => `${row.id} ${row.label}`).join(', ')}`)
  if (argv.includes('--write') || argv.includes('--check')) {
    const doc = fs.readFileSync(DOC, 'utf8')
    const next = spliceDoc(doc, markdown)
    if (argv.includes('--write')) {
      fs.writeFileSync(DOC, next)
      console.log(`wrote ${path.relative(ROOT, DOC)}`)
    } else if (next !== doc) {
      console.error(`${path.relative(ROOT, DOC)} is stale: run node scripts/capability-matrix.mjs --write`)
      return 1
    }
  }
  return 0
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  process.exitCode = main(process.argv.slice(2))
}
